function selectedvideos = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  SELECTEDVIDEOS = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  SELECTEDVIDEOS = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  SELECTEDVIDEOS = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  selectedvideos = importfile("/Users/emily/Dropbox/Research/2020_Sajjad/PhysicalSocial/SocPhys/selected videos.xlsx", "HH_OO stim selected final", [2, 226]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Oct-2021 17:13:18

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 226];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 22);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":V" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "mainCategory", "subcategory", "extentOfAnimacy", "videonum", "OriginalDuration", "ExpDuration", "PropOfHH", "PropOfOO", "PropOfHO", "DevFromPredOfPhysModel", "Intention", "select", "framenumOrig", "avgsporig_x", "avgsporig_7", "framenum1", "avgsp_x", "avgsp_7", "sumSpeed", "Note", "avgspVxvy"];
opts.VariableTypes = ["double", "categorical", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double"];

% Specify variable properties
opts = setvaropts(opts, ["extentOfAnimacy", "Note"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["mainCategory", "extentOfAnimacy", "Note"], "EmptyFieldRule", "auto");

% Import the data
selectedvideos = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":V" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    selectedvideos = [selectedvideos; tb]; %#ok<AGROW>
end

end