function out = importNewPositionData(fname)
% Import data generated by getPosition.py, convert to a more useful format.
% Easier than trying to convert from numpy to matlab.

% Validate input
assert(ischar(fname) || isstring(fname), 'Input must be a filename');
assert(exist(fname, 'file'), 'Could not find file %s', fname);

% Extract output name from input
[~,fout,~] = fileparts(fname);

% Read in data
csv = readtable(fname, 'Delimiter', ',');
csv.Frame = csv.Frame + 1; % because Python starts counting from 0
% csv.ObjectID = csv.ObjectID + 1;

numFrames = max(csv.Frame);
numObjs = max(csv.ObjectID);

% Rotate data 90 degrees
for i = 0:numObjs
    objID = 'objName'; % pull from a list somehow
    used = csv.ObjectID == i;
    X = csv.X(used);
    Y = csv.Y(used);
    frames = csv.Frame(used);

    % Interpolate missing data
    time = 1:numFrames;
    newX = interp1(frames, X, time, 'spline');
    newY = interp1(frames, Y, time, 'cubic', 'extrap');

    % Output
    out{i+1, :} = {fout, objID, newX, newY};
end

end % function